name: neom_jobs
description: Jobs processes for Cyberneom.
version: 1.0.4
homepage: https://github.com/emmanuel-montoya/neom_jobs
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
#  neom_commons:
#    path: ../neom_commons
#  neom_music_player:
#    path: ../neom_music_player
  uuid: 4.1.0
  logger: 2.0.2+1
